
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  server_port: 8321

sensor:
  - platform: command_line
    name: RPI CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(2) }}'

  - platform: bme280
    name: Ambience
    i2c_address: 0x76
    operation_mode: 2  # forced mode
    scan_interval: 40

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature
      - type: last_boot


homekit:
  filter:
    include_entities:
      - sensor.RPI_CPU_Temp
      - binary_sensor.main_door_sensor
      - light.living_room
      - light.tv_room
      - sensor.ambience_humidity
      - sensor.ambience_temperature
  entity_config:
    sensor.RPI_CPU_Temp:
      name: RPI CPU Temp
    binary_sensor.main_door_sensor:
      name: Main Door
    light.living_room:
      name: Living Room
    light.tv_room:
      name: TV
    sensor.ambience_humidity:
      name: Ambient Humidity
    sensor.ambience_temperature:
      name: Ambient Temperature

logger:
  default: info

mqtt:
  discovery: true
  broker: 127.0.0.1

device_tracker:
  - platform: fritz
    host: 192.168.178.1
    username: ********
    password: *********
    interval_seconds: 12
    consider_home: 180
    new_device_defaults:
      track_new_devices: false

telegram_bot:
  - platform: polling
    api_key: **************************
    allowed_chat_ids:
      - ********

notify:
  - platform: telegram
    name: mavuram_telegram
    chat_id: ********

#alert:
#  main_door_alert:
#    name: "Main Door is opened"
#    entity_id: binary_sensor.main_door_sensor
#    state: 'on'
#    repeat: 1
#    can_acknowledge: true
#    skip_first: false
#    notifiers:
#      - mavuram_telegram

automation:
  - alias: Low Ambience temperature alert
    trigger:
      platform: numeric_state
      entity_id: sensor.ambience_temperature  
      #value_template: "{{ states.sensor.ambience_temperature.state }}"
      below: 18
      for: "00:10:00"
    action:
      - service: notify.mavuram_telegram
        data:
          message: "Ambience temperature is Low: {{states.sensor.ambience_temperature.state}}°C"
    mode: single

  - alias: Main Door State
    trigger:
      platform: state
      entity_id: binary_sensor.main_door_sensor
      to: 'on'
    condition:
      - condition: state
        entity_id: 'device_tracker.dilipreplewatch'
        state: 'not_home'
    action:
      - service: notify.mavuram_telegram
        data:
          message: "Main Door is opened"
    mode: single

  - alias: Turn off TV when no one at home
    trigger:
      platform: state
      entity_id: binary_sensor.dilipresiphonex
      to: 'not_home'
    condition:
      - condition: state
        entity_id: 'device_tracker.dilipreplewatch'
        state: 'not_home'
    action:
      - service: notify.mavuram_telegram
        data:
          message: "TV Turned off"
      - service: light.turn_off
        entity_id: light.tv_room
    mode: single
